Repository eclipse-langium/langium, pull requests merged in 2023-10, with the labels that each got.

#1234 Add semantic token type `decorator`
  packages/langium/src/lsp/semantic-token-provider.ts
Labels: LSP

#1237 Update language server libraries to version 9.0
  examples/arithmetics/package.json
  examples/domainmodel/package.json
  examples/requirements/package.json
  examples/statemachine/package.json
  package-lock.json
  packages/generator-langium/test/yeoman-generator.test.ts
  packages/langium-vscode/package.json
  packages/langium/package.json
  packages/langium/test/parser/langium-parser-builder.test.ts
Labels: dependencies

#1240 Remove vscode-uri bundler workaround
  package-lock.json
  packages/langium/package.json
  packages/langium/src/utils/uri-util.ts
Labels: dependencies

#1213 Show all railroad rules in railroad preview
  packages/langium-cli/langium-config-schema.json
  packages/langium-cli/src/generate.ts
  packages/langium-cli/src/package.ts
  packages/langium-railroad/src/grammar-railroad.ts
  packages/langium-vscode/src/language-server/railroad-handler.ts
Labels: extension, railroad

#1241 Treat lines with only comment symbols as empty in JSDoc comments
  packages/langium/src/documentation/jsdoc.ts
  packages/langium/test/documentation/jsdoc.test.ts
Labels: polish
