Repository eclipse-langium/langium, pull requests merged in 2023-05, with the labels that each got.

#1031 Automate release process
  .github/workflows/publish.yml
  CONTRIBUTING.md
  package.json
  scripts/update-version.js
Labels: repo

#1038 Fix missing files in generator
  packages/generator-langium/package.json
  packages/generator-langium/src/index.ts
  packages/generator-langium/templates/cli/.package.json
  packages/generator-langium/templates/cli/bin/cli
  packages/generator-langium/templates/cli/src/cli/cli-util.ts
  packages/generator-langium/templates/cli/src/cli/generator.ts
  packages/generator-langium/templates/cli/src/cli/main.ts
  packages/generator-langium/templates/core/.eslintrc.json
  packages/generator-langium/templates/core/.gitignore
  packages/generator-langium/templates/core/.package.json
  packages/generator-langium/templates/core/.vscode/extensions.json
  packages/generator-langium/templates/core/.vscode/tasks.json
  packages/generator-langium/templates/core/langium-config.json
  packages/generator-langium/templates/core/langium-quickstart.md
  packages/generator-langium/templates/core/src/language/language-id-module.ts
  packages/generator-langium/templates/core/src/language/language-id-validator.ts
  packages/generator-langium/templates/core/src/language/language-id.langium
  packages/generator-langium/templates/core/tsconfig.json
  packages/generator-langium/templates/vscode/.package.json
  packages/generator-langium/templates/vscode/.vscode/launch.json
  packages/generator-langium/templates/vscode/.vscodeignore
  packages/generator-langium/templates/vscode/language-configuration.json
  packages/generator-langium/templates/vscode/src/extension/main.ts
  packages/generator-langium/templates/vscode/src/language/main.ts
  packages/generator-langium/templates/web/.package.json
  packages/generator-langium/templates/web/langium-config.json
  packages/generator-langium/templates/web/src/language/main-browser.ts
  packages/generator-langium/templates/web/src/static/index.html
  packages/generator-langium/templates/web/src/static/setup.js
  packages/generator-langium/templates/web/src/static/styles.css
  packages/generator-langium/templates/web/src/web/app.ts
  packages/generator-langium/templates/web/tsconfig.json
  packages/generator-langium/templates/web/tsconfig.monarch.json
  packages/generator-langium/test/yeoman-generator.test.ts
  scripts/update-version.js
Labels: yeoman

#1040 Another fix for the broken `generator-langium`
  package-lock.json
  packages/generator-langium/package.json
  packages/generator-langium/src/index.ts
  packages/generator-langium/templates/gitignore.txt
Labels: yeoman

#1043 generator/expandToNode: improved handling of white space vs. undefined
  packages/langium/src/generator/template-node.ts
  packages/langium/test/generator/template-node.test.ts
Labels: polish

#1057 Update document url in 'Cycle detected' error message
  packages/langium/src/dependency-injection.ts
  packages/langium/test/dependency-injection.test.ts
Labels: dependency injection
